import turtle

turtle.speed(0)

def draw_hexagon():

    turtle.right(30)
    turtle.forward(20)
    turtle.left(60)
    turtle.forward(20)
    turtle.left(60)
    turtle.forward(20)
    turtle.left(60)
    turtle.forward(20)
    turtle.left(60)
    turtle.forward(20)
    turtle.left(60)
    turtle.forward(20)
    turtle.left(60)
    turtle.forward(20)

    turtle.left(180)
    turtle.forward(20)
    turtle.right(120)
    turtle.forward(20)
    turtle.right(60)
    turtle.forward(20)
    turtle.left(180)
    turtle.forward(20)
    turtle.right(60)
    turtle.forward(20)

turtle.up()
turtle.left(180)
turtle.forward(400)
turtle.right(90)
turtle.forward(400)
turtle.down()

turtle.pencolor('red')
draw_hexagon()
turtle.up()
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(60)
turtle.left(30)
turtle.down()

turtle.pencolor('blue')
draw_hexagon()
turtle.up()
turtle.right(60)
turtle.forward(50)
turtle.left(30)
turtle.down()

turtle.pencolor('green')
draw_hexagon()
turtle.done()
